[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_on_chain_portfolio = "CSg17Be8aubUBAcjroEifZLf5WdFgMWiYBTVmmfxgHPn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nomadic/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
